
name: JitPack Pinger

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Jitpack
        run: curl https://jitpack.io/com/lehaine/kiwi/$(echo $GITHUB_SHA | cut -c1-10)/

